// Cartas de «¿prefieres...?». Cada texto es «A o B»; el motor antepone
// «¿Prefieres» y la minoría del grupo bebe. Contenido a mano, siempre const.
import '../modelo_juegos.dart';

const List<Reto> retosPf = [
  Reto(
    id: 'pf-suave-001',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'pasar un mes sin tu móvil o un mes sin tu música',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-002',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'poder volar o poder hacerte invisible',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-003',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'comer pizza todos los días o no volver a comerla nunca',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-004',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'vivir en la playa o vivir en la montaña',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-005',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'saber leer la mente o poder viajar en el tiempo',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-006',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'no volver a dormir tarde o no volver a madrugar',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-007',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'perder todas tus fotos o perder todos tus contactos',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-suave-008',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'hablar todos los idiomas o tocar todos los instrumentos',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-009',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'llegar siempre diez minutos tarde o siempre veinte antes',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-010',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'cantar todo lo que dices o bailar cada vez que andas',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-suave-011',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'un verano eterno o un invierno eterno',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-012',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'escuchar siempre la misma canción o no escuchar música en un mes',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-013',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'quedarte sin batería en plena noche o sin datos y sin wifi',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-014',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'ser famoso por algo malo o desconocido por algo bueno',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-suave-015',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'ver solo series o ver solo películas el resto de tu vida',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-016',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'tener un súper olfato o una súper vista',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-017',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'cenar siempre de tapeo o siempre en restaurante',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-suave-018',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'que todos lean tus mensajes o que todos vean tu galería',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-suave-019',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'no usar nunca más una red social o no pedir comida a domicilio',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-suave-020',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.suave,
    texto: 'ser el más gracioso del grupo o el más inteligente',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-atrevido-001',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'que tu grupo lea tu historial de búsqueda o tu última conversación',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-002',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'contar tu mayor secreto o inventarte uno que suene peor',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-003',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'que tu madre lea tus chats o que tu ex lea los de ahora',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-atrevido-004',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'cantar a gritos en medio de la pista o bailar un reguetón entero tú solo',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-005',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'mandar un audio de dos minutos a tu crush o no mirarle a los ojos en un mes',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-atrevido-006',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'que tu jefe vea tus stories o que tu familia vea tu noche de ayer',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-007',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'olvidar el cumpleaños de tu mejor amigo o que él olvide el tuyo',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-008',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'salir en la foto de la noche con cara rara o no salir en ninguna',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-atrevido-009',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'llevar un mes la misma ropa en cada salida o cambiarte de peinado cada semana',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-010',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'que te pillen ligando con el amigo de un amigo o con un conocido de tu familia',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-atrevido-011',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'decirle a alguien lo que piensas de verdad de él o que te lo diga él a ti',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-atrevido-012',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'hacerte viral por una caída o por un baile malo',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-013',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'perder la cartera en plena noche o perder las llaves de casa',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-014',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'fingir que te cae bien alguien un año o confesarle que no',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-015',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'que se publique tu mejor foto o tu mejor vídeo bailando',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-016',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'quedarte siempre sin plan o organizarlo tú todo',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-017',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'que te echen de un grupo de WhatsApp o que te silencien en todos',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-atrevido-018',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'contarle a tu pareja un secreto tuyo o a tu mejor amigo uno de tu pareja',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-atrevido-019',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'llegar a casa con todos los vecinos despiertos o sin llaves',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-atrevido-020',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.atrevido,
    texto: 'que el grupo elija tu apodo o tu foto de perfil durante un mes',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-001',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'revelar a quién del grupo elegirías para una aventura o a quién no',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-002',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'que todo el mundo sepa tu mayor vergüenza o tu mayor mentira',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-003',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'escribir a tu ex «te echo de menos» o a tu actual «tenemos que hablar»',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-004',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'que se publique tu conversación más cursi o tu foto más embarazosa',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-005',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'contar con quién de aquí te llevas peor o con quién mejor',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-006',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'ser el último en ligar de la noche o el primero en irte solo',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-007',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'dejar que el grupo elija a quién llamas o a quién escribes',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-008',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'confesar tu mayor mentira en una cita o la mayor excusa que has puesto',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-009',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'que todo el grupo lea tu última nota del móvil o tu último audio',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-010',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto:
        'decir en voz alta tu mayor inseguridad o la de otra persona del grupo',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-011',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'contar la peor noche de tu vida o la más memorable',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-012',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'que te elijan el tipo de persona que ligas o la excusa que pones para irte',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-013',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'saber lo que piensan de ti en este grupo o no saberlo nunca',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-014',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'ser el que más cuenta o el que más calla en esta mesa',
    sorbos: 1,
  ),
  Reto(
    id: 'pf-sinfiltro-015',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'repetir tu peor cita o tu peor entrevista de trabajo',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-016',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'dar una opinión sincera de cada persona del grupo o una mentira piadosa',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-017',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'que alguien del grupo se quede con tu móvil cinco minutos o con tu bolso',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-018',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'que tu mejor amigo cuente tus secretos o los invente',
    sorbos: 3,
  ),
  Reto(
    id: 'pf-sinfiltro-019',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto: 'pasar una semana sin quejarte o una semana sin mentir',
    sorbos: 2,
  ),
  Reto(
    id: 'pf-sinfiltro-020',
    juego: TipoJuego.preferirias,
    nivel: NivelReto.sinFiltro,
    texto:
        'que tu primera impresión de alguien de aquí fuera cierta o equivocada',
    sorbos: 1,
  ),
];
