// Cartas de "quién es más probable". Contenido generado a mano, siempre const.
import '../modelo_juegos.dart';

const List<Reto> retosMp = [
  Reto(
    id: 'mp-suave-001',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'llegue tarde a su propia boda',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-002',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se quede dormido en el cine',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-003',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'pierda el móvil esta noche',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-004',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'acabe cantando en el karaoke sin que se lo pidan',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-005',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se ponga a bailar encima de una silla',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-006',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se pida un desayuno a las cinco de la mañana',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-007',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se olvide del cumpleaños de su mejor amigo',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-008',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se enamore de alguien que ha conocido hoy',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-009',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'termine siendo famoso en redes',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-010',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se pierda yendo a un sitio que ya conoce',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-011',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'cuente un secreto sin querer',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-012',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'llore viendo una película de dibujos animados',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-013',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se quede en casa en vez de salir un sábado',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-014',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'llegue el primero a la previa y se vaya el último',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-015',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'ponga la peor canción de la noche',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-016',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se gaste el sueldo en ropa en una sola tarde',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-017',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se ponga a hacer un bailecito en la cola de un súper',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-018',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'acabe haciendo amigos con el portero de la discoteca',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-019',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se olvide de dónde ha dejado el abrigo',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-020',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'confunda el nombre de alguien tres veces en una noche',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-021',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'mande un mensaje al chat equivocado',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-022',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se ría en un momento serio',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-023',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se pase la noche haciéndose fotos',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-024',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se quede hablando con el perro de alguien toda la fiesta',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-025',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'pida perdón por algo que no ha hecho',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-suave-026',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se ponga a dar consejos a desconocidos',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-027',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'sea el que más tarde en contestar a un mensaje',
    sorbos: 1,
  ),
  Reto(
    id: 'mp-suave-028',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.suave,
    texto: 'se haga viral por algo ridículo',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-001',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'acabe ligando con el camarero o camarera',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-atrevido-002',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'tenga más matches que nadie en Tinder',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-003',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'escriba a su ex esta noche',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-004',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'mienta en una cita para parecer más interesante',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-005',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'acabe enrollándose con alguien de este grupo',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-atrevido-006',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'se vaya de la fiesta sin despedirse para irse con alguien',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-007',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'suba una foto de esta noche que luego se arrepienta',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-008',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'se enfade por celos sin motivo',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-009',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'sea el más celoso de una pareja',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-atrevido-010',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'se enamore del amigo de un amigo',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-011',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'tenga una cita de madrugada con alguien que no conocía',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-012',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'use una frase de ligue penosa y le funcione',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-013',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'sea el que más ligues tenga de aquí',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-atrevido-014',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'sea el último en admitir que le gusta alguien',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-015',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'se líe con alguien de una app de citas esta semana',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-016',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'haga stalking a un ligue hasta encontrar a su abuela en Facebook',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-017',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'vuelva con un ex por aburrimiento',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-atrevido-018',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'se presente a una cita con el pelo hecho un desastre',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-019',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'se líe con el primero que le sonría en una discoteca',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-020',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'dé un número de teléfono falso',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-021',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'sea el que más mensajes de madrugada manda',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-atrevido-022',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'se convierta en el mejor amigo de un ex',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-023',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'acabe llorando en el baño de una discoteca',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-024',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'sea el que nunca contesta a los audios largos',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-025',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'pida la canción que más vergüenza da en medio de la pista',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-atrevido-026',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'acabe durmiendo en el sofá de alguien que acaba de conocer',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-027',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'lleve un año sin ligar y diga que es por elección',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-028',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'termine casándose con su primer amor',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-atrevido-029',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.atrevido,
    texto: 'sea el más intenso con un ligue',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-001',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'se haya enrollado con alguien y a los dos días ni se acuerde',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-002',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'mantenga a dos ligues a la vez',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-003',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'tenga el historial de citas más desastroso',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-004',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'sea el peor para guardar un secreto',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-005',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'le monten un drama por una foto de sus stories',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-006',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'acabe peleado con un ex por una tontería de la última fiesta',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-007',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'mire el móvil de su pareja a escondidas',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-008',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'se líe con el ex de un amigo',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-009',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'sea el más infiel en una relación, sin quererlo',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-010',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'haya tenido un rollo secreto del que nadie sabe nada',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-011',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'tenga la peor red flag de todo el grupo',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-012',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'sea el primero en casarse y el primero en divorciarse',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-013',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'llame a un ex borracho de madrugada',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-014',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'se haya enamorado de alguien que no le hacía ni caso',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-015',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'haya estado con alguien de este grupo',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-016',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'acabe metiéndose en un lío de parejas',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-017',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'presuma de ligar más de lo que liga',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-018',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'haya pasado la peor noche de su vida por culpa de un ligue',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-019',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'sea el que más mentiras cuenta al ligar',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-020',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'termine odiando a un ex por pura rabia',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-021',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'se haya hecho pasar por otra persona en una app',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-022',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'sea el más lanzado en una fiesta',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-023',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'acabe con el corazón roto este mes',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-024',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'se líe con un famoso si se le presentara la ocasión',
    sorbos: 2,
  ),
  Reto(
    id: 'mp-sinfiltro-025',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'se lo pase mejor en una cita que en una boda',
    sorbos: 3,
  ),
  Reto(
    id: 'mp-sinfiltro-026',
    juego: TipoJuego.masProbable,
    nivel: NivelReto.sinFiltro,
    texto: 'sea el más cotilla del grupo',
    sorbos: 2,
  ),
];
