// Cartas de "yo nunca". Contenido generado a mano, siempre const.
import '../modelo_juegos.dart';

const List<Reto> retosYn = [
  Reto(
    id: 'yn-suave-001',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he comido pizza a las cuatro de la mañana',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-suave-002',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'me he quedado dormido en el transporte público y me he pasado de parada',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-003',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he mandado un mensaje a la persona equivocada',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-004',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he fingido que me gustaba una canción para caer bien',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-suave-005',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'me he perdido en una ciudad que no conocía',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-006',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he llegado tarde a una cita por estar eligiendo ropa',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-007',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he roto algo en casa ajena y no lo he dicho',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-suave-008',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he cantado a pleno pulmón en la calle',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-009',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he bailado solo delante del espejo',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-010',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he dicho que estaba de camino y seguía en la ducha',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-suave-011',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he pedido una copa y me la he derramado encima',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-012',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he puesto una excusa falsa para no ir a un plan',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-013',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'me he dormido en una fiesta',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-suave-014',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he hecho una foto a un menú solo para enseñarla',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-015',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he stalkeado a alguien durante más de una hora',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-016',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he perdido el móvil y lo tenía en la mano',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-suave-017',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'me he quedado sin batería justo cuando más lo necesitaba',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-018',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he dicho "ahora voy" y me he quedado en el sofá',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-019',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he ido a una fiesta sin conocer a casi nadie',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-suave-020',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he cambiado de planes por un mensaje de última hora',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-021',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he hecho un selfie y he borrado veinte antes de subir uno',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-022',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he rechazado una invitación a una boda solo por pereza',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-suave-023',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'me he equivocado de nombre al saludar a alguien',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-suave-024',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.suave,
    texto: 'he seguido a alguien por Instagram y lo he dejado de seguir al día siguiente',
    sorbos: 1,
  ),
  Reto(
    id: 'yn-atrevido-001',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he mirado el móvil de mi pareja sin que lo supiera',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-atrevido-002',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he escrito a mi ex estando de fiesta',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-003',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he mentido en mi perfil de una app de citas',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-004',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he dejado a alguien en visto a propósito durante días',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-005',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'me he enrollado con alguien de mi grupo de amigos',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-atrevido-006',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he dicho "te quiero" sin sentirlo del todo',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-007',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto:
        'he tenido un rollo de una noche y al día siguiente fingí no conocerle',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-008',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he ligado en el gimnasio',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-009',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he fingido estar ocupado para no contestar a un ligue',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-atrevido-010',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he hablado mal de alguien del grupo a sus espaldas',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-011',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he hecho match con alguien conocido en Tinder y fingí no verle',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-012',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he vuelto con un ex y me he arrepentido en una semana',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-013',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he salido de fiesta en pijama por error o por desafío',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-atrevido-014',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he llorado en un baño de discoteca',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-015',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'me han pillado mirando a alguien demasiado tiempo',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-016',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he pedido una canción para ligar con alguien',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-017',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto:
        'he hecho una llamada o un mensaje de madrugada de los que se lamentan',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-atrevido-018',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he soñado con alguien de este grupo',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-019',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he fingido un dolor de cabeza para irme de una cita',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-020',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he dado un número falso a alguien que me pretendía',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-021',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he tenido celos de un amigo o amiga de mi pareja',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-atrevido-022',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he revisado las stories de alguien que me gusta más de tres veces seguidas',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-023',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he ido a una cita sin ganas solo por no quedar mal',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-024',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'me he arrepentido de un tatuaje o de un corte de pelo hecho en plena fiesta',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-atrevido-025',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.atrevido,
    texto: 'he quedado con alguien conocido por una app y fue un desastre',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-001',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto:
        'me he enrollado con alguien y al día siguiente no recordaba su nombre',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-002',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he tenido un rollo con el amigo o la amiga de mi ex',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-003',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he salido con dos personas a la vez sin que ninguna lo supiera',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-004',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he borrado conversaciones para que no me pillaran',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-005',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he ido a una fiesta sabiendo que iba a encontrarme con mi ex',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-006',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he fingido estar enfermo para no ver a mi ligue',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-007',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he usado una app de citas teniendo pareja',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-008',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he vuelto a casa y no recordaba cómo llegué',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-009',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he cotilleado el móvil de un ligue mientras dormía',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-010',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he llamado por otro nombre a alguien en un momento íntimo',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-011',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'me he despertado en casa de alguien sin saber cómo llegué ahí',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-012',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he dicho "me gustas" a alguien y luego me he hecho el loco',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-013',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he hecho algo en una fiesta de lo que tengo que escaparme cuando se habla',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-014',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'me han pillado mintiendo en una cita y he seguido mintiendo',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-015',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he escrito "te echo de menos" a un ex a las cuatro de la mañana',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-016',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he fingido que tenía pareja para quitarme a alguien de encima',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-017',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he ligado con alguien en el trabajo y lo he ocultado',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-018',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he dejado a alguien plantado sin avisar',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-019',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto:
        'he subido una story de fiesta de la que me arrepentí al día siguiente',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-020',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto:
        'me he dado cuenta de que me gustaba alguien justo cuando tenía pareja',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-021',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he pasado la noche con alguien y no he contestado a su mensaje después',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-022',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he tenido celos de alguien de este grupo',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-023',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he mandado un audio larguísimo por WhatsApp del que me avergüenzo',
    sorbos: 3,
  ),
  Reto(
    id: 'yn-sinfiltro-024',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he hablado con mi ex mientras estaba con otra persona',
    sorbos: 2,
  ),
  Reto(
    id: 'yn-sinfiltro-025',
    juego: TipoJuego.yoNunca,
    nivel: NivelReto.sinFiltro,
    texto: 'he fingido un desmayo o un mareo para acabar una cita',
    sorbos: 3,
  ),
];
