// Cartas de "no hay huevos". Contenido generado a mano, siempre const.
import '../modelo_juegos.dart';

const List<Reto> retosNhh = [
  Reto(
    id: 'nhh-suave-001',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Haz una ola mexicana tú solo con los brazos durante diez segundos',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-002',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Cuenta qué serías si fueras un electrodoméstico y por qué',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-003',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Dile a {otro} una frase motivadora de taza de desayuno con mucha pasión',
    sorbos: 1,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-004',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Llama a un número al azar de tus contactos y cántale el himno de tu equipo',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-005',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Imita a otra persona del grupo durante un minuto hasta que alguien adivine quién es',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-006',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Haz tu mejor baile de TikTok sin música durante 20 segundos',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-007',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Habla con acento argentino hasta tu próximo turno',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-008',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Enseña la última foto de tu galería sin mirarla antes',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-009',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Cuenta un chiste malo con toda la seriedad del mundo',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-010',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Haz una declaración de amor dramática a un cojín o a una planta',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-011',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Imita a un presentador de telediario dando la noticia de esta previa',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-012',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Canta el estribillo de una canción del verano pasado con toda la emoción',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-013',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Habla como un locutor de radio nocturna durante un minuto',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-014',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Haz un desfile de modelo por el salón como si fuera la Fashion Week',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-015',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Pon una cara de susto, una de amor y una de asco en diez segundos',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-016',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Di tu mayor mentira de fiesta con total convicción',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-017',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Enseña tu última búsqueda en Google sin borrarla',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-018',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Hazle un baile de bienvenida a {otro} como si acabara de llegar de un viaje eterno',
    sorbos: 1,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-019',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Cuenta el peor ridículo que hayas pasado en una discoteca',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-020',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Escribe en tus notas un poema de tres versos sobre {otro} y léelo en voz alta',
    sorbos: 1,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-021',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Enseña tu canción más vergonzosa de tu lista de reproducción y cántala un poco',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-022',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Habla en tercera persona hasta que te toque otra vez',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-023',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Haz de comentarista deportivo narrando cómo {otro} bebe un sorbo',
    sorbos: 1,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-024',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Enseña el último sticker que hayas mandado por WhatsApp',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-025',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Di tres cosas que te encantan de {otro} sin reírte',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-026',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Finge que eres un influencer y haz un unboxing de tu propio vaso',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-027',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Mantén el contacto visual con {otro} durante diez segundos sin reírte',
    sorbos: 1,
    contactoFisico: true,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-028',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Di un trabalenguas difícil tres veces seguidas sin equivocarte',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-029',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Inventa un anuncio de televisión para vender el mando de la tele',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-030',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Haz una reverencia a cada persona del grupo diciendo su nombre con voz solemne',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-031',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Cuenta qué harías si tuvieras un superpoder inútil y hazlo a la vez con mímica',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-032',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Habla con la voz de un dibujo animado hasta la siguiente ronda',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-033',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Enseña a los demás cómo bailas cuando crees que nadie te mira',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-034',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Haz tu mejor imitación de un famoso y que el grupo adivine quién es',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-035',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Cuenta tu peor cita a ciegas como si fuera una película de terror',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-036',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Haz un brindis exageradamente emotivo por la previa',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-037',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Dedícale una canción a {otro} cantando un trozo a capela',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-038',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Da un discurso de agradecimiento como si hubieras ganado un Goya',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-039',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Haz una pose de foto de grupo ridícula y mantenla 15 segundos',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-040',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Enseña tu último selfie y explica por qué salió tan mal',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-041',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Dile a {otro} cómo te lo imaginas de aquí a diez años, sin cortarte',
    sorbos: 1,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-042',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Imita el balido de una cabra cada vez que alguien diga tu nombre en la próxima ronda',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-043',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Haz de azafata de vuelo explicando las normas de seguridad de esta previa',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-044',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Di el nombre de todos los presentes con un apodo inventado y absurdo',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-045',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Sorprende a {otro} con un choque de manos épico de los que se ensayan',
    sorbos: 1,
    contactoFisico: true,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-046',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Imita a tu profesor o profesora más pesado mientras explicas las reglas de un juego',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-047',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Habla solo con preguntas durante tres minutos o bebe',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-048',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Cuenta la anécdota más absurda que te haya pasado de resaca',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-049',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Haz un anuncio de cortes de pelo de los años ochenta con pose y todo',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-suave-050',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Di "te quiero" con cara de enfado a la primera persona que te mire',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-051',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Explica con dibujos en el aire cómo llegaste a casa la última vez que saliste',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-052',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto:
        'Haz una escena de novela venezolana con {otro} durante medio minuto',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-suave-053',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Adivina a quién del grupo le pasó algo vergonzoso hoy, por pura intuición',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-054',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Hazle una reverencia a la persona de tu derecha y dile "a sus órdenes"',
    sorbos: 1,
  ),
  Reto(
    id: 'nhh-suave-055',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.suave,
    texto: 'Describe tu outfit de esta noche como si fueras comentarista de alfombra roja',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-001',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta cuál fue tu primera cita y qué hiciste mal',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-002',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di qué canción pondrías para ligar con alguien de la sala y dedícasela',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-003',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Enseña cuál es el último emoji que usaste con alguien que te gusta',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-004',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di cuál es tu frase de ligue favorita y úsala con {otro} en broma',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-005',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Enseña el último mensaje que te mandó tu ex, sin mandar nada y sin decir quién es si no quieres',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-006',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Abre Tinder o la app de citas que uses y enseña tu primer match en pantalla',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-007',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Lee en voz alta tu último chat de WhatsApp con un ligue, sin tapar nada',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-008',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Haz un baile sensual de tres segundos delante de todos, vestido y con dignidad',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-009',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di en voz alta con quién del grupo saldrías de fiesta toda una noche, sin pensarlo',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-010',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta quién de la sala te parece más atractivo sin pasarte de gracioso',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-011',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Enseña tu historial de citas más desastroso: la peor frase que te han soltado ligando',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-012',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Mírale a los ojos a {otro} diez segundos y dile algo bonito sin reírte',
    sorbos: 2,
    contactoFisico: true,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-013',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Déjale a {otro} elegir una canción y baila como si fuera tu canción de boda',
    sorbos: 3,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-014',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di el peor plan de ligue que hayas intentado y cómo acabó',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-015',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta con detalle tu peor momento de celos, sin decir nombres si no quieres',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-016',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Finge una llamada con tu ligue ideal y mantén la conversación un minuto entero',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-017',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Enseña la foto más vieja que tengas con un ex en tu galería, con el ex tapado si quieres',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-018',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di quién del grupo sería el peor compañero de piso y por qué, con cariño',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-019',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta el mensaje más cringe que has mandado borracho o borracha',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-020',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Déjale el móvil a {otro} 30 segundos para que vea tu pantalla de inicio y tus apps',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-021',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Haz de galán o galana de serie turca mirando a {otro} durante veinte segundos',
    sorbos: 3,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-022',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di cuál es tu mayor red flag sin disimular',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-023',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta la mentira más gorda que has dicho para quitarte a alguien de encima',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-024',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Enseña tu foto de perfil de Instagram más antigua y cuenta qué pensabas entonces',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-025',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di cuántas personas te has dejado en visto esta semana y por qué',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-026',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Escribe a alguien del grupo un mensaje de ligue cutre y léelo con voz seductora',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-027',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta con quién tuviste tu primer rollo de verano sin dar datos que le dañen',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-028',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Ponle nota del uno al diez a la forma de bailar de cada persona del grupo, con cariño',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-029',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di a quién del grupo no dejarías nunca a solas con tu ligue',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-030',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Haz una confesión pública: algo que nunca le hayas contado a nadie de aquí',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-031',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Enseña cuántas conversaciones tienes sin responder en tu WhatsApp',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-032',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto:
        'Imita cómo ligas tú en una discoteca, con gestos y frases incluidas',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-033',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Dile a {otro} qué es lo primero que pensaste de él o ella cuando os conocisteis',
    sorbos: 3,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-034',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Haz un baile de reggaetón de diez segundos con toda la cara',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-035',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta qué harías si tu ex te escribiera ahora mismo a las cuatro de la mañana',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-036',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di una cosa por la que nunca perdonarías a un ligue',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-037',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Enseña tu lista de canciones de "superar a un ex" y canta una',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-038',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta tu rollo más inesperado sin dar nombres',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-039',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Dile a {otro} un piropo original y que suene sincero',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-040',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta si alguna vez te han pillado mirando el móvil de tu pareja o ligue',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-041',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di cuál es la mentira que más usas para salir antes de un plan aburrido',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-042',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Dile a {otro} que te lo has pasado genial hoy, pero con voz de culebrón',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-043',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta qué mensaje te gustaría recibir ahora mismo y de quién',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-044',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Elige a alguien del grupo con quien harías una cita a ciegas y explica por qué',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-045',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Enseña tus tres últimas fotos de stories sin editar nada',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-046',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di la peor excusa que has puesto para cancelar una cita',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-047',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Recita tu declaración de amor más cursi como si fuera un bolero',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-048',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta cuál ha sido tu mayor plantón o que te lo hayan dado',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-049',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto:
        'Di quién del grupo tiene mejor estilo para ligar y cuál es su truco',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-050',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Inventa una frase de ligue para cada persona del grupo, con buen rollo',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-051',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Haz tu cara de "me gusta alguien" y que el grupo adivine a quién miras',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-052',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuenta qué es lo más loco que has hecho por un ligue',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-053',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di cuántas veces has mirado el perfil de tu ex este mes',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-054',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto:
        'Enseña la última persona que has bloqueado y di por qué sin nombrarla',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-055',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Haz un mini discurso de padrino o madrina de boda sobre {otro} sin cortarte',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-056',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Di con quién te casarías, te enrollarías y saldrías de fiesta de entre los presentes',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-057',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Haz un ranking de ligues de tu vida en orden y justifica el número uno sin dar nombres',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-atrevido-058',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Chocad los cinco {otro} y tú como si fuerais una pareja de baile profesional',
    sorbos: 2,
    contactoFisico: true,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-atrevido-059',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto: 'Cuéntanos una cosa que hayas hecho por parecer más interesante en una cita',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-atrevido-060',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.atrevido,
    texto:
        'Habla tres minutos como si fueras un coach de seducción de internet',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-001',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Enseña la conversación más vergonzosa que tengas guardada con un ligue, tapando nombres y fotos',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-002',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di en voz alta quién del grupo crees que ligaría antes esta noche y por qué',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-003',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto:
        'Cuenta tu peor escena de celos como si fuera una película dramática',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-004',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta la cosa más loca que has hecho en una fiesta, sin pasarte de detalles',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-005',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di qué persona del grupo sería tu peor error de una noche y cuál tu mejor',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-006',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Enseña todos los mensajes de "¿estás despierto?" que hayas mandado o recibido, con nombres tapados',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-007',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di cuál es tu mayor inseguridad al ligar y cómo la disimulas',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-008',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Confiesa una mentira que contaste a tus amigos y que sigue sin saberse',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-009',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta qué hiciste la última vez que tuviste una resaca épica y de qué te arrepentiste',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-010',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto:
        'Di si alguna vez has fingido una llamada para escaparte de una cita',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-011',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Deja que el grupo elija una cita de tu galería de fotos antiguas y cuéntala entera',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-012',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta quién del grupo te cae mejor y quién te cae peor y por qué, con humor',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-013',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto:
        'Dile a {otro} lo que más te irrita de salir de fiesta con él o ella',
    sorbos: 3,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-sinfiltro-014',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Haz la imitación de tu ex y de cómo os peleabais, sin nombrarle',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-015',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Confiesa a quién del grupo le has mirado el Instagram de más',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-016',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta qué harías si pudieras revivir una noche de fiesta para cambiar algo',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-017',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto:
        'Enseña el chat con más mensajes sin leer y lee el último en voz alta',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-018',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di tres cosas de tu último ligue que te sacaban de quicio',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-019',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta cuál ha sido la vez que más has tenido que mentir para salir de una cita',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-020',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Haz tu mejor llanto dramático de "te fuiste sin decirme nada"',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-021',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di si alguna vez has hablado mal de alguien del grupo sin que lo sepa, y de qué iba',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-022',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta el mayor cotilleo que sepas y por el que podrías meterte en líos, sin nombres',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-023',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Confiesa qué es lo más loco que has buscado en el móvil de tu pareja o ligue',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-024',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto:
        'Di a quién llamarías ahora mismo si tuvieras un momento de debilidad',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-025',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Enseña tus tres últimas búsquedas en Instagram y explica por qué esas personas',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-026',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di cuál es la mayor mentira de tu perfil de citas y por qué la pusiste',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-027',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuéntanos tu día más humillante por culpa de un ligue',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-028',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto:
        'Elige a alguien del grupo y dile a la cara tu mejor y tu peor defecto',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-029',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di a quién del grupo le darías tu contraseña del móvil y a quién nunca',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-030',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di cuál ha sido tu mejor momento de gloria en una discoteca y el peor, sin cortarte',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-031',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta cuántas veces has lloreado por un ligue y cuál fue el motivo más tonto',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-032',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto:
        'Haz una confesión que haga reír a todos: tu mayor paranoia de pareja',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-033',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di si alguna vez te has enamorado de alguien que tenía pareja, sin nombres',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-034',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Explica con quién del grupo compartirías un viaje de ocho horas y con quién jamás',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-035',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Lee en voz alta la última nota de tu móvil, sea cual sea',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-036',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Enseña el último mensaje de tu ex pero solo si te apetece, sin mandar nada a nadie',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-037',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di tu récord de mensajes seguidos sin respuesta y qué decían',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-038',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Enseña en tu móvil el contacto que tienes guardado con el nombre más vergonzoso y explica por qué',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-039',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Haz una ronda de "la verdad del grupo": dile a cada uno una cosa que admiras y una que cambiarías',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-040',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di cuál ha sido el mensaje más comprometedor que has mandado al chat equivocado',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-041',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta con quién te has sentido más incómodo o incómoda en una cita y por qué',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-042',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Di qué pensó tu último ligue de ti, según tú, y si tenía razón',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-043',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Dile a {otro} qué rumor sobre ti crees que corre por ahí y si es verdad',
    sorbos: 3,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'nhh-sinfiltro-044',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto:
        'Di quién del grupo sería el peor en una cita contigo y quién el mejor',
    sorbos: 2,
  ),
  Reto(
    id: 'nhh-sinfiltro-045',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Cuenta el secreto más tonto que jamás le has contado a tus amigos',
    sorbos: 3,
  ),
  Reto(
    id: 'nhh-sinfiltro-046',
    juego: TipoJuego.noHayHuevos,
    nivel: NivelReto.sinFiltro,
    texto: 'Reta a {otro} a un duelo de miradas de quince segundos sin reír: el que pierda bebe',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
];
