// Cartas de "verdad o reto". Contenido generado a mano, siempre const.
import '../modelo_juegos.dart';

const List<Reto> retosVr = [
  Reto(
    id: 'vr-suave-001',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿cuál es la canción que más te avergüenza que te guste?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-suave-002',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿cuál ha sido tu mayor ridículo en público?',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-003',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿qué es lo más raro que has buscado en Google?',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-004',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿cuál es tu mayor miedo absurdo?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-suave-005',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿qué persona del grupo te hace reír más?',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-006',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿cuál fue el peor regalo que recibiste y qué cara pusiste?',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-007',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿has mentido alguna vez para librarte de una cita? ¿Cómo fue?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-suave-008',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: haz tu mejor imitación de una persona del grupo hasta que la adivinen',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-009',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: canta el estribillo de una canción con voz de ópera',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-010',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: haz un baile de dos minutos sin música al ritmo de tu cabeza',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-suave-011',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: habla con acento gallego hasta tu siguiente turno',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-012',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: cuenta un chiste y que nadie se ría, o bebe',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-013',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: pon cara de poker y aguanta un minuto mientras {otro} te cuenta un chiste',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'vr-suave-014',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: haz cinco poses de modelo diferentes en quince segundos',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-015',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: haz un brindis a {otro} como si fuera vuestra boda',
    sorbos: 1,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'vr-suave-016',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿qué harías con un millón de euros en una semana?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-suave-017',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿cuál es la mentira más tonta que has dicho esta semana?',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-018',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Verdad: ¿has llorado alguna vez viendo un anuncio?',
    sorbos: 1,
  ),
  Reto(
    id: 'vr-suave-019',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: enseña la última foto que hayas sacado sin borrarla',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-suave-020',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.suave,
    texto: 'Reto: cuéntale a {otro} lo que más te gusta de él o ella en voz solemne',
    sorbos: 1,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'vr-atrevido-001',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿cuál es el piropo más cutre que has soltado alguna vez?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-atrevido-002',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿cuál ha sido tu peor cita y por qué?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-003',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿a quién del grupo le darías un diez como ligue?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-004',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿con quién de los presentes irías de viaje a una isla desierta?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-005',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿cuál es tu mayor red flag al ligar?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-atrevido-006',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿has stalkeado a un ex recientemente? ¿Cuánto hace?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-007',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿cuál ha sido tu rollo más inesperado?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-008',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿has tenido celos de algún amigo de tu pareja o ligue?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-009',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿qué es lo más loco que has hecho por amor?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-atrevido-010',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: enseña el último mensaje de tu ex sin mandar nada y sin decir quién es si no quieres',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-011',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: enseña el último match que hayas hecho en una app de citas',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-012',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: mira a {otro} a los ojos diez segundos y dile algo bonito',
    sorbos: 2,
    contactoFisico: true,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'vr-atrevido-013',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: haz un baile sensual de cinco segundos, vestido y con dignidad',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-atrevido-014',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: lee en voz alta tu último chat de WhatsApp con alguien que te guste',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-015',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: deja que el grupo elija tu foto de perfil de WhatsApp durante la previa',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-016',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: haz un ranking de los ligues que has tenido sin decir nombres',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-017',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿qué es lo que más te gusta de ligar en una discoteca?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-atrevido-018',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: abraza diez segundos a {otro} como si se fuera a la guerra',
    sorbos: 2,
    contactoFisico: true,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'vr-atrevido-019',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿cuál ha sido tu peor plantón?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-020',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: imita cómo ligas tú, con frases y gestos',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-atrevido-021',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Verdad: ¿has fingido estar ocupado para no contestar a alguien? ¿A quién?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-atrevido-022',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.atrevido,
    texto: 'Reto: haz una declaración de amor a {otro} con cara de culebrón',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'vr-sinfiltro-001',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿qué es lo más vergonzoso que te ha pasado con un ligue?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-002',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿cuál es el secreto que jamás has contado a tus amigos?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-sinfiltro-003',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿de quién del grupo te has sentido celoso alguna vez?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-004',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿quién del grupo crees que ligaría menos esta noche y por qué?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-sinfiltro-005',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿has mentido en una app de citas? Cuéntanos qué pusiste',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-006',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿qué harías si tu ex te escribiera ahora mismo?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-sinfiltro-007',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿a quién del grupo no dejarías a solas con tu pareja?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-008',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿cuál es tu mayor arrepentimiento de una noche de fiesta?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-sinfiltro-009',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿has hablado mal alguna vez de alguien de aquí? ¿De quién y de qué?',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-010',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Verdad: ¿qué es lo más loco que has buscado en el móvil de tu pareja?',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-sinfiltro-011',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Reto: enseña tus últimas búsquedas de Instagram y explica por qué esas personas',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-012',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Reto: dile a {otro} lo que más te irrita de él o ella, con cariño',
    sorbos: 2,
    necesitaOtraPersona: true,
  ),
  Reto(
    id: 'vr-sinfiltro-013',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Reto: enseña tu conversación más vergonzosa con un ligue, con nombres tapados',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-014',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Reto: elige a alguien del grupo y dile tu mejor y tu peor defecto',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-sinfiltro-015',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Reto: lee en voz alta la última nota de tu móvil, sea cual sea',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-016',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Reto: haz una confesión que haga reír a todos sobre tu vida amorosa',
    sorbos: 2,
  ),
  Reto(
    id: 'vr-sinfiltro-017',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Reto: cuéntanos un cotilleo del que te arrepientas, sin dar nombres',
    sorbos: 3,
  ),
  Reto(
    id: 'vr-sinfiltro-018',
    juego: TipoJuego.verdadOReto,
    nivel: NivelReto.sinFiltro,
    texto: 'Reto: mírale a los ojos a {otro} quince segundos y dile qué piensas de él o ella, con respeto',
    sorbos: 2,
    contactoFisico: true,
    necesitaOtraPersona: true,
  ),
];
